name = "ProcessModelAnalyzer"
uuid = "7bc7cd7e-b284-46f4-8c84-8736db20d1bb"
version = "0.1.0"
authors = ["mosnyan <tony.arseneault.1@ulaval.ca>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
Interpolations = "0.16.2"
Optimization = "5.4.0"
OptimizationBBO = "0.4.5"
OptimizationOptimJL = "0.4.9"
